//GET /api ✅
//GET /api/topics ✅
//GET /api/articles ✅
//GET /api/articles/:article_id ✅
//GET /api/articles/:article_id/comments ✅
//POST /api/articles/:article_id/comments ✅
//PATCH /api/articles/:article_id ✅
//DELETE /api/comments/:comment_id ✅
//GET /api/users ✅
